# Generated by Django 2.2 on 2019-05-19 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0002_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contents',
            name='place',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contents',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.Content'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lesson.Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Content'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
