# Generated by Django 2.2 on 2019-05-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_questionrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
