# Generated by Django 2.2 on 2019-04-09 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='decription',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='content.Content'),
            preserve_default=False,
        ),
    ]
