# Generated by Django 2.2 on 2019-05-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_fullfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_of_visits',
            field=models.IntegerField(default=0),
        ),
    ]
